site_name: ZeppelinHub
site_url: https://www.zeppelinhub.com/
site_description: ZeppelinHub Documentation 
site_author: Ahyoung Ryu from NFLabs
site_favicon: favicon.ico

# repo_url: https://github.com/NFLabs/zeppelinhub-documentation

pages:
- Home: index.md
- Overview: overview.md
- Introduction:
    - Managing your ZeppelinHub Account: zeppelinhub_account.md
    - Zeppelin & ZeppelinHub Integration: zeppelin_integration.md
- User Guide: 
    - Sharing your Notebooks: sharing_notebooks.md
    - Copying the Notebooks: copying_notebooks.md
- What is ZeppelinHub Viewer: zeppelinhub_viewer.md
- Zeppelin Multitenancy: zeppelin_multitenancy.md
- Support: support.md

theme: readthedocs

#extra_css: css/extra.css
