# Site Information
site_name: ZeppelinHub
site_url: http://help.zeppelinhub.com/
site_description: ZeppelinHub Documentation Site
site_author: NFLabs
site_favicon: favicon.ico

# repo_url: https://github.com/NFLabs/zeppelinhub-documentation

# Included pages list
pages:
- Introduction: index.md
- Key Concepts: overview.md
- User Guide: 
    - ZeppelinHub Account: zeppelinhub_account.md
    - Zeppelin & ZeppelinHub Integration: zeppelin_integration.md
    - Sharing Notebooks: sharing_notebooks.md
    - Copying Notebooks: copying_notebooks.md
    - ZeppelinHub Viewer: zeppelinhub_viewer.md
    - Zeppelin Multitenancy: zeppelin_multitenancy.md
- Support: support.md

# Theme & Javascript & CSS
theme_dir: 'custom_theme'
extra_javascript:  
  - js/extra.js
extra_css: 
  - css/extra.css
